# Generated by Django 3.2.15 on 2022-12-19 09:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinfo',
            name='no_of_assets',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelinfo',
            name='travel_medium',
            field=models.CharField(choices=[('bus', 'bus'), ('car', 'car'), ('train', 'train')], default='bus', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelinfo',
            name='traveling_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 19, 9, 2, 25, 18290, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
