# Generated by Django 3.2.15 on 2022-12-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_auto_20221219_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinfo',
            name='ride_accepted_by',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name="Ride accepted by the Person's Detail"),
        ),
        migrations.AddField(
            model_name='travelinfo',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('not_applied', 'not_applied')], default='applied', max_length=30),
        ),
    ]
