# Generated by Django 3.2.15 on 2022-12-19 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
        ('rider', '0003_auto_20221219_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelinfo',
            name='ride_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='util.rideinfo'),
            preserve_default=False,
        ),
    ]
