# Generated by Django 3.2.15 on 2022-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0005_auto_20221219_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelinfo',
            name='status',
            field=models.CharField(choices=[('applied', 'applied'), ('not_applied', 'not_applied')], default='not_applied', max_length=30),
        ),
    ]
