# Generated by Django 3.2.15 on 2022-12-19 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=500, verbose_name='Asset to be Picked From')),
                ('destination', models.CharField(max_length=500, verbose_name='Asset Delivered to')),
                ('date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
