# Generated by Django 3.2.15 on 2022-12-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportationrequest',
            name='accepted_person',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name="Transportation Request accepted by the Person's Detail"),
        ),
        migrations.AlterField(
            model_name='transportationrequest',
            name='status',
            field=models.CharField(choices=[('confirm', 'confirm'), ('pending', 'pending'), ('expired', 'expired')], default='pending', max_length=50),
        ),
    ]
