# Generated by Django 3.2.15 on 2022-12-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0002_auto_20221219_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationrequest',
            name='accepted_person',
        ),
    ]
