# Generated by Django 3.2.15 on 2022-12-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requester', '0004_transportationrequest_ride_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportationrequest',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='transportationrequest',
            name='pick_on',
        ),
        migrations.RemoveField(
            model_name='transportationrequest',
            name='source',
        ),
    ]
